/* A recursive-descent parser generated by peg 0.1.15 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 32
#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_EscapedPCRE(yycontext *yy); /* 32 */
YY_RULE(int) yy_PCRE(yycontext *yy); /* 31 */
YY_RULE(int) yy_Value(yycontext *yy); /* 30 */
YY_RULE(int) yy_ValueList(yycontext *yy); /* 29 */
YY_RULE(int) yy_Colon(yycontext *yy); /* 28 */
YY_RULE(int) yy_RegEx(yycontext *yy); /* 27 */
YY_RULE(int) yy_Only(yycontext *yy); /* 26 */
YY_RULE(int) yy_LogicalOr(yycontext *yy); /* 25 */
YY_RULE(int) yy_Range(yycontext *yy); /* 24 */
YY_RULE(int) yy_Any(yycontext *yy); /* 23 */
YY_RULE(int) yy_ClosingBracket(yycontext *yy); /* 22 */
YY_RULE(int) yy_ValueReference(yycontext *yy); /* 21 */
YY_RULE(int) yy_Dot(yycontext *yy); /* 20 */
YY_RULE(int) yy_OpenBracket(yycontext *yy); /* 19 */
YY_RULE(int) yy_OptDepends(yycontext *yy); /* 18 */
YY_RULE(int) yy_IfDepends(yycontext *yy); /* 17 */
YY_RULE(int) yy_Space(yycontext *yy); /* 16 */
YY_RULE(int) yy_Number(yycontext *yy); /* 15 */
YY_RULE(int) yy_TagReference(yycontext *yy); /* 14 */
YY_RULE(int) yy_Digit(yycontext *yy); /* 13 */
YY_RULE(int) yy_Values(yycontext *yy); /* 12 */
YY_RULE(int) yy_Requirements(yycontext *yy); /* 11 */
YY_RULE(int) yy_Semicolon(yycontext *yy); /* 10 */
YY_RULE(int) yy_Tag(yycontext *yy); /* 9 */
YY_RULE(int) yy_EndOfLine(yycontext *yy); /* 8 */
YY_RULE(int) yy_MiscUntilEOL(yycontext *yy); /* 7 */
YY_RULE(int) yy_Tagline(yycontext *yy); /* 6 */
YY_RULE(int) yy_SpaceLine(yycontext *yy); /* 5 */
YY_RULE(int) yy_Comment(yycontext *yy); /* 4 */
YY_RULE(int) yy_EndOfFile(yycontext *yy); /* 3 */
YY_RULE(int) yy_Line(yycontext *yy); /* 2 */
YY_RULE(int) yy_start(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_Any(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Any\n"));
  {
   set_any(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_RegEx\n"));
  {
   set_parse_error("expects an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_RegEx\n"));
  {
   set_parse_error("expects an open '\"'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_RegEx\n"));
  {
   set_parse_error("expects a PCRE-regex", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_RegEx\n"));
  {
   set_parse_error("expects a closing '\"'", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_RegEx\n"));
  {
   set_parse_error("expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_RegEx(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_RegEx\n"));
  {
   set_regex( yytext ); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Only\n"));
  {
   set_parse_error("values expects an open bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Only\n"));
  {
   set_parse_error("values expects a value list", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Only\n"));
  {
   set_parse_error("values expects a closing bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Only(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Only\n"));
  {
   set_only(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ValueReference\n"));
  {
   set_parse_error("value reference error: '%s'", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ValueReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ValueReference\n"));
  {
   set_any_reference(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Value(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Value\n"));
  {
   incr_values(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_LogicalOr(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_LogicalOr\n"));
  {
   set_parse_error("values expects an open bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_LogicalOr(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_LogicalOr\n"));
  {
   set_parse_error("values expects a value list", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_LogicalOr(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_LogicalOr\n"));
  {
   set_parse_error("values expects a closing bracket", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_LogicalOr(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LogicalOr\n"));
  {
   set_logical_or(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ClosingBracket(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ClosingBracket\n"));
  {
   set_parse_error("missed closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OpenBracket(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OpenBracket\n"));
  {
   set_parse_error("missed open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Dot(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Dot\n"));
  {
   set_parse_error("missed dot", yytext);
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Colon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Colon\n"));
  {
   set_parse_error("missed colon", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Number\n"));
  {
   set_parse_error("number expected", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Number(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Number\n"));
  {
   i_push(atol(yytext) );;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_Range\n"));
  {
   set_parse_error("values expects an open bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Range\n"));
  {
   set_parse_error("values expects a number", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Range\n"));
  {
   set_parse_error("values expects a colon", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Range\n"));
  {
   set_parse_error("values expects a number", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Range\n"));
  {
   set_parse_error("values expects a closing bracket", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Range(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Range\n"));
  {
  set_range(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Values(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Values\n"));
  {
   set_parse_error("wrong values-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_OptDepends\n"));
  {
   set_parse_error("requirement expects an open bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_OptDepends\n"));
  {
   set_parse_error("requirement expects a tagreference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_OptDepends\n"));
  {
   set_parse_error("requirement expects a dot",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_OptDepends\n"));
  {
   set_parse_error("requirement expects a value reference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_OptDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OptDepends\n"));
  {
   set_parse_error("requirement expects a closing bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_IfDepends\n"));
  {
   set_parse_error("requirement expects an open bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_IfDepends\n"));
  {
   set_parse_error("requirement expects a tagreference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_IfDepends\n"));
  {
   set_parse_error("requirement expects a dot",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_IfDepends\n"));
  {
   set_parse_error("requirement expects a value reference",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_IfDepends(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IfDepends\n"));
  {
   set_parse_error("requirement expects a closing bracket",  yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Requirements\n"));
  {
   set_parse_error("wrong requirements-keyword", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Requirements\n"));
  {
   set_optional(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Requirements\n"));
  {
   set_optdepends(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Requirements\n"));
  {
   set_ifdepends(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Requirements(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Requirements\n"));
  {
   set_mandatory(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Semicolon(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Semicolon\n"));
  {
   set_parse_error("missed semicolon", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_TagReference(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_TagReference\n"));
  {
   set_parse_error("wrong tagreference", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Tag(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Tag\n"));
  {
   set_parse_error("wrong tag", yytext);;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Tag(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Tag\n"));
  {
  
                        int tag = atoi(yytext);
                        /* rule_tagorder_in_dsl( tag ); */
                        settag( tag );
                ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_Tagline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_Tagline\n"));
  {
   set_parse_error("tagline expects missed semicolon here", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_Tagline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_Tagline\n"));
  {
   set_parse_error("tagline requires a requiemrent-keyword (mandatory, etc.)",yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Tagline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Tagline\n"));
  {
   set_parse_error("tagline expects missed semicolon here", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Tagline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Tagline\n"));
  {
   set_parse_error("tagline requires values", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Tagline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Tagline\n"));
  {
   set_parse_error( "tagline requires EOL", yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Tagline(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Tagline\n"));
  {
   rule_addtag_config(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_Line(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_Line\n"));
  {
   set_parse_error("wrong line entry",yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_Line(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_Line\n"));
  {
   incrlineno(); tagline(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_Line(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_Line\n"));
  {
   incrlineno(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Line(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Line\n"));
  {
   incrlineno(); commentline(); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_EscapedPCRE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EscapedPCRE"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l3;  if (!yymatchChar(yy, '\\')) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '\\')) goto l1;  if (!yymatchChar(yy, '"')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EscapedPCRE", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EscapedPCRE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCRE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCRE"));
  {  int yypos5= yy->__pos, yythunkpos5= yy->__thunkpos;  if (!yy_EscapedPCRE(yy)) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos5; yy->__thunkpos= yythunkpos5;  if (!yymatchClass(yy, (unsigned char *)"\377\377\377\377\373\377\377\377\377\377\377\357\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l4;
  }
  l5:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PCRE", yy->__buf+yy->__pos));
  return 1;
  l4:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCRE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Value(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Value"));  if (!yy_Number(yy)) goto l7;  yyDo(yy, yy_1_Value, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Value", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ValueList(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ValueList"));  if (!yy_Value(yy)) goto l8;
  l9:;	
  {  int yypos10= yy->__pos, yythunkpos10= yy->__thunkpos;  if (!yy_Colon(yy)) goto l10;  if (!yy_Value(yy)) goto l10;  goto l9;
  l10:;	  yy->__pos= yypos10; yy->__thunkpos= yythunkpos10;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "ValueList", yy->__buf+yy->__pos));
  return 1;
  l8:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ValueList", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Colon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Colon"));
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l13;
  l14:;	
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;  if (!yy_Space(yy)) goto l15;  goto l14;
  l15:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;
  }  goto l12;
  l13:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l11;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l11;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l11;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Colon, yy->__begin, yy->__end);
  }
  l12:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Colon", yy->__buf+yy->__pos));
  return 1;
  l11:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Colon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_RegEx(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "RegEx"));
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yymatchString(yy, "regex")) goto l18;  if (!yy_OpenBracket(yy)) goto l18;  if (!yymatchChar(yy, '"')) goto l18;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l18;
#undef yytext
#undef yyleng
  }
  l19:;	
  {  int yypos20= yy->__pos, yythunkpos20= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l20;  goto l19;
  l20:;	  yy->__pos= yypos20; yy->__thunkpos= yythunkpos20;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l18;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l18;  if (!yy_ClosingBracket(yy)) goto l18;  yyDo(yy, yy_1_RegEx, yy->__begin, yy->__end);  goto l17;
  l18:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;  if (!yymatchString(yy, "regex")) goto l21;  if (!yy_OpenBracket(yy)) goto l21;  if (!yymatchChar(yy, '"')) goto l21;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l21;
#undef yytext
#undef yyleng
  }
  l22:;	
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l23;  goto l22;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l21;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l21;  yyDo(yy, yy_2_RegEx, yy->__begin, yy->__end);  goto l17;
  l21:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;  if (!yymatchString(yy, "regex")) goto l24;  if (!yy_OpenBracket(yy)) goto l24;  if (!yymatchChar(yy, '"')) goto l24;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l24;
#undef yytext
#undef yyleng
  }
  l25:;	
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yy_PCRE(yy)) goto l26;  goto l25;
  l26:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l24;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_RegEx, yy->__begin, yy->__end);  goto l17;
  l24:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;  if (!yymatchString(yy, "regex")) goto l27;  if (!yy_OpenBracket(yy)) goto l27;  if (!yymatchChar(yy, '"')) goto l27;  yyDo(yy, yy_4_RegEx, yy->__begin, yy->__end);  goto l17;
  l27:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;  if (!yymatchString(yy, "regex")) goto l28;  if (!yy_OpenBracket(yy)) goto l28;  yyDo(yy, yy_5_RegEx, yy->__begin, yy->__end);  goto l17;
  l28:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;  if (!yymatchString(yy, "regex")) goto l16;  yyDo(yy, yy_6_RegEx, yy->__begin, yy->__end);
  }
  l17:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "RegEx", yy->__buf+yy->__pos));
  return 1;
  l16:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RegEx", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Only(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Only"));
  {  int yypos30= yy->__pos, yythunkpos30= yy->__thunkpos;  if (!yymatchString(yy, "only")) goto l31;  if (!yy_OpenBracket(yy)) goto l31;  if (!yy_ValueList(yy)) goto l31;  if (!yy_ClosingBracket(yy)) goto l31;  yyDo(yy, yy_1_Only, yy->__begin, yy->__end);  goto l30;
  l31:;	  yy->__pos= yypos30; yy->__thunkpos= yythunkpos30;  if (!yymatchString(yy, "only")) goto l32;  if (!yy_OpenBracket(yy)) goto l32;  if (!yy_ValueList(yy)) goto l32;  yyDo(yy, yy_2_Only, yy->__begin, yy->__end);  goto l30;
  l32:;	  yy->__pos= yypos30; yy->__thunkpos= yythunkpos30;  if (!yymatchString(yy, "only")) goto l33;  if (!yy_OpenBracket(yy)) goto l33;  yyDo(yy, yy_3_Only, yy->__begin, yy->__end);  goto l30;
  l33:;	  yy->__pos= yypos30; yy->__thunkpos= yythunkpos30;  if (!yymatchString(yy, "only")) goto l29;  yyDo(yy, yy_4_Only, yy->__begin, yy->__end);
  }
  l30:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Only", yy->__buf+yy->__pos));
  return 1;
  l29:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Only", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LogicalOr(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "LogicalOr"));
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yymatchString(yy, "logical_or")) goto l36;  if (!yy_OpenBracket(yy)) goto l36;  if (!yy_ValueList(yy)) goto l36;  if (!yy_ClosingBracket(yy)) goto l36;  yyDo(yy, yy_1_LogicalOr, yy->__begin, yy->__end);  goto l35;
  l36:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "logical_or")) goto l37;  if (!yy_OpenBracket(yy)) goto l37;  if (!yy_ValueList(yy)) goto l37;  yyDo(yy, yy_2_LogicalOr, yy->__begin, yy->__end);  goto l35;
  l37:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "logical_or")) goto l38;  if (!yy_OpenBracket(yy)) goto l38;  yyDo(yy, yy_3_LogicalOr, yy->__begin, yy->__end);  goto l35;
  l38:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;  if (!yymatchString(yy, "logical_or")) goto l34;  yyDo(yy, yy_4_LogicalOr, yy->__begin, yy->__end);
  }
  l35:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "LogicalOr", yy->__buf+yy->__pos));
  return 1;
  l34:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogicalOr", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Range(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Range"));
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yymatchString(yy, "range")) goto l41;  if (!yy_OpenBracket(yy)) goto l41;  if (!yy_Number(yy)) goto l41;  if (!yy_Colon(yy)) goto l41;  if (!yy_Number(yy)) goto l41;  if (!yy_ClosingBracket(yy)) goto l41;  yyDo(yy, yy_1_Range, yy->__begin, yy->__end);  goto l40;
  l41:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yymatchString(yy, "range")) goto l42;  if (!yy_OpenBracket(yy)) goto l42;  if (!yy_Number(yy)) goto l42;  if (!yy_Colon(yy)) goto l42;  if (!yy_Number(yy)) goto l42;  yyDo(yy, yy_2_Range, yy->__begin, yy->__end);  goto l40;
  l42:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yymatchString(yy, "range")) goto l43;  if (!yy_OpenBracket(yy)) goto l43;  if (!yy_Number(yy)) goto l43;  if (!yy_Colon(yy)) goto l43;  yyDo(yy, yy_3_Range, yy->__begin, yy->__end);  goto l40;
  l43:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yymatchString(yy, "range")) goto l44;  if (!yy_OpenBracket(yy)) goto l44;  if (!yy_Number(yy)) goto l44;  yyDo(yy, yy_4_Range, yy->__begin, yy->__end);  goto l40;
  l44:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yymatchString(yy, "range")) goto l45;  if (!yy_OpenBracket(yy)) goto l45;  yyDo(yy, yy_5_Range, yy->__begin, yy->__end);  goto l40;
  l45:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;  if (!yymatchString(yy, "range")) goto l39;  yyDo(yy, yy_6_Range, yy->__begin, yy->__end);
  }
  l40:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Range", yy->__buf+yy->__pos));
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Range", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Any(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Any"));  if (!yymatchString(yy, "any")) goto l46;  yyDo(yy, yy_1_Any, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 1;
  l46:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Any", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ClosingBracket(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ClosingBracket"));
  {  int yypos48= yy->__pos, yythunkpos48= yy->__thunkpos;  if (!yymatchChar(yy, ')')) goto l49;  goto l48;
  l49:;	  yy->__pos= yypos48; yy->__thunkpos= yythunkpos48;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l47;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l47;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l47;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_ClosingBracket, yy->__begin, yy->__end);
  }
  l48:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ClosingBracket", yy->__buf+yy->__pos));
  return 1;
  l47:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ClosingBracket", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ValueReference(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ValueReference"));
  {  int yypos51= yy->__pos, yythunkpos51= yy->__thunkpos;  if (!yymatchString(yy, "any")) goto l52;  yyDo(yy, yy_1_ValueReference, yy->__begin, yy->__end);  goto l51;
  l52:;	  yy->__pos= yypos51; yy->__thunkpos= yythunkpos51;  if (!yy_Number(yy)) goto l53;  goto l51;
  l53:;	  yy->__pos= yypos51; yy->__thunkpos= yythunkpos51;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l50;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l50;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l50;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_ValueReference, yy->__begin, yy->__end);
  }
  l51:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "ValueReference", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ValueReference", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Dot(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Dot"));
  {  int yypos55= yy->__pos, yythunkpos55= yy->__thunkpos;  if (!yymatchChar(yy, '.')) goto l56;
  l57:;	
  {  int yypos58= yy->__pos, yythunkpos58= yy->__thunkpos;  if (!yy_Space(yy)) goto l58;  goto l57;
  l58:;	  yy->__pos= yypos58; yy->__thunkpos= yythunkpos58;
  }  goto l55;
  l56:;	  yy->__pos= yypos55; yy->__thunkpos= yythunkpos55;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l54;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l54;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l54;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Dot, yy->__begin, yy->__end);
  }
  l55:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Dot", yy->__buf+yy->__pos));
  return 1;
  l54:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Dot", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OpenBracket(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OpenBracket"));
  {  int yypos60= yy->__pos, yythunkpos60= yy->__thunkpos;  if (!yymatchChar(yy, '(')) goto l61;  goto l60;
  l61:;	  yy->__pos= yypos60; yy->__thunkpos= yythunkpos60;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l59;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l59;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l59;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_OpenBracket, yy->__begin, yy->__end);
  }
  l60:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "OpenBracket", yy->__buf+yy->__pos));
  return 1;
  l59:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OpenBracket", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OptDepends(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OptDepends"));
  {  int yypos63= yy->__pos, yythunkpos63= yy->__thunkpos;  if (!yymatchString(yy, "optdepends")) goto l64;  if (!yy_OpenBracket(yy)) goto l64;  if (!yy_TagReference(yy)) goto l64;  if (!yy_Dot(yy)) goto l64;  if (!yy_ValueReference(yy)) goto l64;  if (!yy_ClosingBracket(yy)) goto l64;  goto l63;
  l64:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yymatchString(yy, "optdepends")) goto l65;  if (!yy_OpenBracket(yy)) goto l65;  if (!yy_TagReference(yy)) goto l65;  if (!yy_Dot(yy)) goto l65;  if (!yy_ValueReference(yy)) goto l65;  yyDo(yy, yy_1_OptDepends, yy->__begin, yy->__end);  goto l63;
  l65:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yymatchString(yy, "optdepends")) goto l66;  if (!yy_OpenBracket(yy)) goto l66;  if (!yy_TagReference(yy)) goto l66;  if (!yy_Dot(yy)) goto l66;  yyDo(yy, yy_2_OptDepends, yy->__begin, yy->__end);  goto l63;
  l66:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yymatchString(yy, "optdepends")) goto l67;  if (!yy_OpenBracket(yy)) goto l67;  if (!yy_TagReference(yy)) goto l67;  yyDo(yy, yy_3_OptDepends, yy->__begin, yy->__end);  goto l63;
  l67:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yymatchString(yy, "optdepends")) goto l68;  if (!yy_OpenBracket(yy)) goto l68;  yyDo(yy, yy_4_OptDepends, yy->__begin, yy->__end);  goto l63;
  l68:;	  yy->__pos= yypos63; yy->__thunkpos= yythunkpos63;  if (!yymatchString(yy, "optdepends")) goto l62;  yyDo(yy, yy_5_OptDepends, yy->__begin, yy->__end);
  }
  l63:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "OptDepends", yy->__buf+yy->__pos));
  return 1;
  l62:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OptDepends", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IfDepends(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IfDepends"));
  {  int yypos70= yy->__pos, yythunkpos70= yy->__thunkpos;  if (!yymatchString(yy, "depends")) goto l71;  if (!yy_OpenBracket(yy)) goto l71;  if (!yy_TagReference(yy)) goto l71;  if (!yy_Dot(yy)) goto l71;  if (!yy_ValueReference(yy)) goto l71;  if (!yy_ClosingBracket(yy)) goto l71;  goto l70;
  l71:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;  if (!yymatchString(yy, "depends")) goto l72;  if (!yy_OpenBracket(yy)) goto l72;  if (!yy_TagReference(yy)) goto l72;  if (!yy_Dot(yy)) goto l72;  if (!yy_ValueReference(yy)) goto l72;  yyDo(yy, yy_1_IfDepends, yy->__begin, yy->__end);  goto l70;
  l72:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;  if (!yymatchString(yy, "depends")) goto l73;  if (!yy_OpenBracket(yy)) goto l73;  if (!yy_TagReference(yy)) goto l73;  if (!yy_Dot(yy)) goto l73;  yyDo(yy, yy_2_IfDepends, yy->__begin, yy->__end);  goto l70;
  l73:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;  if (!yymatchString(yy, "depends")) goto l74;  if (!yy_OpenBracket(yy)) goto l74;  if (!yy_TagReference(yy)) goto l74;  yyDo(yy, yy_3_IfDepends, yy->__begin, yy->__end);  goto l70;
  l74:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;  if (!yymatchString(yy, "depends")) goto l75;  if (!yy_OpenBracket(yy)) goto l75;  yyDo(yy, yy_4_IfDepends, yy->__begin, yy->__end);  goto l70;
  l75:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;  if (!yymatchString(yy, "depends")) goto l69;  yyDo(yy, yy_5_IfDepends, yy->__begin, yy->__end);
  }
  l70:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IfDepends", yy->__buf+yy->__pos));
  return 1;
  l69:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IfDepends", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Space(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Space"));
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l78;  goto l77;
  l78:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;  if (!yymatchChar(yy, '\t')) goto l76;
  }
  l77:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 1;
  l76:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Space", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Number(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Number"));
  {  int yypos80= yy->__pos, yythunkpos80= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l81;
#undef yytext
#undef yyleng
  }  if (!yy_Digit(yy)) goto l81;
  l82:;	
  {  int yypos83= yy->__pos, yythunkpos83= yy->__thunkpos;  if (!yy_Digit(yy)) goto l83;  goto l82;
  l83:;	  yy->__pos= yypos83; yy->__thunkpos= yythunkpos83;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l81;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Number, yy->__begin, yy->__end);  goto l80;
  l81:;	  yy->__pos= yypos80; yy->__thunkpos= yythunkpos80;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l79;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l79;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l79;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_Number, yy->__begin, yy->__end);
  }
  l80:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 1;
  l79:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Number", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_TagReference(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "TagReference"));
  {  int yypos85= yy->__pos, yythunkpos85= yy->__thunkpos;  if (!yy_Number(yy)) goto l86;  goto l85;
  l86:;	  yy->__pos= yypos85; yy->__thunkpos= yythunkpos85;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l84;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l84;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l84;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_TagReference, yy->__begin, yy->__end);
  }
  l85:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "TagReference", yy->__buf+yy->__pos));
  return 1;
  l84:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TagReference", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Digit(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Digit"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;
  yyprintf((stderr, "  ok   %s @ %s\n", "Digit", yy->__buf+yy->__pos));
  return 1;
  l87:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Digit", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Values(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Values"));
  {  int yypos89= yy->__pos, yythunkpos89= yy->__thunkpos;  if (!yy_Any(yy)) goto l90;  goto l89;
  l90:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  if (!yy_Range(yy)) goto l91;  goto l89;
  l91:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  if (!yy_LogicalOr(yy)) goto l92;  goto l89;
  l92:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  if (!yy_Only(yy)) goto l93;  goto l89;
  l93:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  if (!yy_RegEx(yy)) goto l94;  goto l89;
  l94:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l88;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l88;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l88;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Values, yy->__begin, yy->__end);
  }
  l89:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Values", yy->__buf+yy->__pos));
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Values", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Requirements(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Requirements"));
  {  int yypos96= yy->__pos, yythunkpos96= yy->__thunkpos;  if (!yymatchString(yy, "mandatory")) goto l97;  yyDo(yy, yy_1_Requirements, yy->__begin, yy->__end);  goto l96;
  l97:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  if (!yy_IfDepends(yy)) goto l98;  yyDo(yy, yy_2_Requirements, yy->__begin, yy->__end);  goto l96;
  l98:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  if (!yy_OptDepends(yy)) goto l99;  yyDo(yy, yy_3_Requirements, yy->__begin, yy->__end);  goto l96;
  l99:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  if (!yymatchString(yy, "optional")) goto l100;  yyDo(yy, yy_4_Requirements, yy->__begin, yy->__end);  goto l96;
  l100:;	  yy->__pos= yypos96; yy->__thunkpos= yythunkpos96;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l95;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l95;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l95;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_5_Requirements, yy->__begin, yy->__end);
  }
  l96:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Requirements", yy->__buf+yy->__pos));
  return 1;
  l95:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Requirements", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Semicolon(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Semicolon"));
  {  int yypos102= yy->__pos, yythunkpos102= yy->__thunkpos;  if (!yymatchChar(yy, ';')) goto l103;
  l104:;	
  {  int yypos105= yy->__pos, yythunkpos105= yy->__thunkpos;  if (!yy_Space(yy)) goto l105;  goto l104;
  l105:;	  yy->__pos= yypos105; yy->__thunkpos= yythunkpos105;
  }  goto l102;
  l103:;	  yy->__pos= yypos102; yy->__thunkpos= yythunkpos102;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l101;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l101;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l101;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Semicolon, yy->__begin, yy->__end);
  }
  l102:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Semicolon", yy->__buf+yy->__pos));
  return 1;
  l101:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Semicolon", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Tag(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Tag"));
  {  int yypos107= yy->__pos, yythunkpos107= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l108;
#undef yytext
#undef yyleng
  }  if (!yy_Digit(yy)) goto l108;
  l109:;	
  {  int yypos110= yy->__pos, yythunkpos110= yy->__thunkpos;  if (!yy_Digit(yy)) goto l110;  goto l109;
  l110:;	  yy->__pos= yypos110; yy->__thunkpos= yythunkpos110;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l108;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_Tag, yy->__begin, yy->__end);  goto l107;
  l108:;	  yy->__pos= yypos107; yy->__thunkpos= yythunkpos107;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l106;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l106;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l106;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_Tag, yy->__begin, yy->__end);
  }
  l107:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Tag", yy->__buf+yy->__pos));
  return 1;
  l106:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Tag", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EndOfLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EndOfLine"));
  {  int yypos112= yy->__pos, yythunkpos112= yy->__thunkpos;  if (!yymatchString(yy, "\r\n")) goto l113;  goto l112;
  l113:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yymatchChar(yy, '\n')) goto l114;  goto l112;
  l114:;	  yy->__pos= yypos112; yy->__thunkpos= yythunkpos112;  if (!yymatchChar(yy, '\r')) goto l111;
  }
  l112:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EndOfLine", yy->__buf+yy->__pos));
  return 1;
  l111:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EndOfLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_MiscUntilEOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "MiscUntilEOL"));  if (!yymatchClass(yy, (unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l115;
  l116:;	
  {  int yypos117= yy->__pos, yythunkpos117= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\377\333\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377\377")) goto l117;  goto l116;
  l117:;	  yy->__pos= yypos117; yy->__thunkpos= yythunkpos117;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "MiscUntilEOL", yy->__buf+yy->__pos));
  return 1;
  l115:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MiscUntilEOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Tagline(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Tagline"));
  {  int yypos119= yy->__pos, yythunkpos119= yy->__thunkpos;  if (!yy_Tag(yy)) goto l120;  if (!yy_Semicolon(yy)) goto l120;  if (!yy_Requirements(yy)) goto l120;  if (!yy_Semicolon(yy)) goto l120;  if (!yy_Values(yy)) goto l120;  if (!yy_EndOfLine(yy)) goto l120;  yyDo(yy, yy_1_Tagline, yy->__begin, yy->__end);  goto l119;
  l120:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_Tag(yy)) goto l121;  if (!yy_Semicolon(yy)) goto l121;  if (!yy_Requirements(yy)) goto l121;  if (!yy_Semicolon(yy)) goto l121;  if (!yy_Values(yy)) goto l121;  yyDo(yy, yy_2_Tagline, yy->__begin, yy->__end);  goto l119;
  l121:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_Tag(yy)) goto l122;  if (!yy_Semicolon(yy)) goto l122;  if (!yy_Requirements(yy)) goto l122;  if (!yy_Semicolon(yy)) goto l122;  yyDo(yy, yy_3_Tagline, yy->__begin, yy->__end);  goto l119;
  l122:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_Tag(yy)) goto l123;  if (!yy_Semicolon(yy)) goto l123;  if (!yy_Requirements(yy)) goto l123;  yyDo(yy, yy_4_Tagline, yy->__begin, yy->__end);  goto l119;
  l123:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_Tag(yy)) goto l124;  if (!yy_Semicolon(yy)) goto l124;  yyDo(yy, yy_5_Tagline, yy->__begin, yy->__end);  goto l119;
  l124:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;  if (!yy_Tag(yy)) goto l118;  yyDo(yy, yy_6_Tagline, yy->__begin, yy->__end);
  }
  l119:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Tagline", yy->__buf+yy->__pos));
  return 1;
  l118:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Tagline", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SpaceLine(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SpaceLine"));
  {  int yypos126= yy->__pos, yythunkpos126= yy->__thunkpos;  if (!yy_Space(yy)) goto l126;  goto l127;
  l126:;	  yy->__pos= yypos126; yy->__thunkpos= yythunkpos126;
  }
  l127:;	  if (!yy_EndOfLine(yy)) goto l125;
  yyprintf((stderr, "  ok   %s @ %s\n", "SpaceLine", yy->__buf+yy->__pos));
  return 1;
  l125:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SpaceLine", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Comment(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Comment"));  if (!yymatchChar(yy, '#')) goto l128;
  l129:;	
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;
  {  int yypos131= yy->__pos, yythunkpos131= yy->__thunkpos;  if (!yy_EndOfLine(yy)) goto l131;  goto l130;
  l131:;	  yy->__pos= yypos131; yy->__thunkpos= yythunkpos131;
  }  if (!yymatchDot(yy)) goto l130;  goto l129;
  l130:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;
  }  if (!yy_EndOfLine(yy)) goto l128;
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment", yy->__buf+yy->__pos));
  return 1;
  l128:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EndOfFile(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EndOfFile"));
  {  int yypos133= yy->__pos, yythunkpos133= yy->__thunkpos;  if (!yymatchDot(yy)) goto l133;  goto l132;
  l133:;	  yy->__pos= yypos133; yy->__thunkpos= yythunkpos133;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EndOfFile", yy->__buf+yy->__pos));
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EndOfFile", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Line(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "Line"));
  {  int yypos135= yy->__pos, yythunkpos135= yy->__thunkpos;  if (!yy_Comment(yy)) goto l136;  yyDo(yy, yy_1_Line, yy->__begin, yy->__end);  goto l135;
  l136:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;  if (!yy_SpaceLine(yy)) goto l137;  yyDo(yy, yy_2_Line, yy->__begin, yy->__end);  goto l135;
  l137:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;  if (!yy_Tagline(yy)) goto l138;  yyDo(yy, yy_3_Line, yy->__begin, yy->__end);  goto l135;
  l138:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l134;
#undef yytext
#undef yyleng
  }  if (!yy_MiscUntilEOL(yy)) goto l134;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l134;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_4_Line, yy->__begin, yy->__end);
  }
  l135:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 1;
  l134:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Line", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_start(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "start"));  if (!yy_Line(yy)) goto l139;
  l140:;	
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yy_Line(yy)) goto l141;  goto l140;
  l141:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;
  }  if (!yy_EndOfFile(yy)) goto l139;
  yyprintf((stderr, "  ok   %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 1;
  l139:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_start);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
